[package]
name = "pomodoro-rs"
version = "0.1.0"
authors = ["Michele Lacchia <michelelacchia@gmail.com>"]
license = "ISC"
edition = "2018"

description = "A lightweight pomodoro timer"
homepage = "https://github.com/rubik/pomodoro-rs"
repository = "https://github.com/rubik/pomodoro-rs"

[dependencies]
